### PR TITLE
[HOLD] Release 8.0.0 changes

### PR DESCRIPTION
**Pull request by tonidero**
This is the base branch for all 8.0.0 changes

### CODE REVIEW

**Comment by EinfachHans** [comment]
Can someone fetch the latest main changes and release beta 2 so that the changes from `7.5.9` apply as well? 😊

**Comment by EinfachHans** [comment]
@tonidero you know what i'm about to ask right? 😅

**Comment by tonidero** [comment]
@EinfachHans We just released 8.0.0-beta.4 with the latest changes from the stable release. Thanks for letting us know :)

**Review by hassain4444 — APPROVED** [review]

**Comment by skkap** [comment]
(Just a quick sharing from a user)
I was able to integrate 8.0.0-beta.4 with my Capacitor 6 application on iOS.

**Comment by braincomb** [comment]
@tonidero Looking forward to using `DEFERRED`. Any ETA when that can be merged into the next 8.x beta? Thanks.

**Comment by tonidero** [comment]
We just released the stable version 8.0.0 with Capacitor V6 support so closing this PR. Thanks all for your patience!

**Pull request closed without merging**
